### ISSUE TITLE
AWS: service persists after cleanup

### ISSUE THREAD

**Issue by itowlson** [fermyon/installer#65]
I did an AWS install and did some testing of deployment stuff.  Some time later, I did a `terraform destroy` as was specified for tearing down resources, but it reported

```
09:05 $ terraform destroy

No changes. No objects need to be destroyed.

Either you have not created any objects yet or the existing objects were already deleted outside of Terraform.

Destroy complete! Resources: 0 destroyed.
```

I thought this might be because my AWS login token had expired so I logged back in and recreated the environment variables, but still got the same response.

I believe the services are still there because my deployed Spin application is still responding to requests.

**Comment by itowlson** [comment]
Is `terraform.tfstate` meant to hold the resources to destroy?  There's nothing where and I can't see anything I did that might have emptied it.

```
09:21 $ cat terraform.tfstate
{
  "version": 4,
  "terraform_version": "1.2.3",
  "serial": 1,
  "lineage": "737ad313-182c-47c9-4fec-e980ff50b59b",
  "outputs": {},
  "resources": []
}
```

**Comment by itowlson** [comment]
I'm looking at my region (`us-west-1`) and there are a bunch of instances but there seem to be multiples.  Am I seeing instances for the whole company?  Or are they just mine (in which case I can safely tear them down).

![image](https://user-images.githubusercontent.com/865538/174680468-4717f810-8292-4280-884e-8489b4f31af1.png)

**Comment by lann** [comment]
If you're logged into your company account, it's instances for the whole company. @vdice

**Comment by itowlson** [comment]
That's what I thought; I will restrain myself from rampaging.

**Comment by vdice** [comment]
> Is terraform.tfstate meant to hold the resources to destroy? There's nothing where and I can't see anything I did that might have emptied it.

Indeed, this file tracks state for terraform.  It should be populated with all of the resources created from `terraform apply`.  My first suggestion is to check your working directory to be sure you're in the same dir that `terraform apply` was initially run from.  Otherwise, we definitely want to figure out what may have caused this behavior.

For manual cleanup, all resources are named using the designated `instance_name` variable.  It looks like `fermyon-hashistack` was used (this was the default a little while ago).  See [here](https://github.com/fermyon/installer/tree/main/aws#resources-deployed) for the resources to delete.  They consist of:
- The EC2 instance: `fermyon-hashistack` in this case
- The Elastic IP resource: `fermyon-hashistack-eip` in this case
- The Security Group: `fermyon-hashistack-security-group` in this case
- The SSH Keypair: `fermyon-hashistack_ssh_key_pair` in this case

**Comment by lann** [comment]
It might be nice to tag all the instances with something like `FermyonInstaller = <installer start timestamp>`, even just for our internal use.

**Comment by itowlson** [comment]
@vdice aha!  The bash history (the only thing in the house not destroyed by a kitten over the weekend) shows that I originally ran `apply` from `aws/terraform`, but ran `destroy` from `aws`.  Thank you for catching this.  It is now merrily tearing down.

PEBKAC, closing.

**Comment by vdice** [comment]
Ah, thanks for the update @itowlson and sorry about the house 😹 

Still, navigating away from the directory where the local Terraform state is located and then running `terraform <command>` is definitely common (I do it often).  We can/should improve awareness here; tangentially related: https://github.com/fermyon/installer/issues/23
